### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by brandly** [brandly/irc#16]
i like dark UIs but idk if i have the design skills to pull one off. i could probably steal some dark grays from another app and repurpose them here.

there should be a settings page where you can toggle between the two

**Comment by xvilo** [comment]
I can take a look at it @brandly is it still being actively maintained? Not any recent commits and some open PR's with no discussions or whatsoever

**Comment by brandly** [comment]
hey! i'm glad to have a true designer looking at this stuff :D 

i go though phases of working on this project for a bit and then leaving it alone for a while. if you get a nice design in place, i can help wire up a settings page to allow switching to dark mode.

thanks for helping out!
