### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by matikbird** [brandly/irc#2]
Tried to npm install in linux and windows.
The screen remains blank..

**Comment by mrozbarry** [comment]
I'm on osx, I installed with `yarn`, ran with `yarn start`, and everything was working. I doubt it's an issue with `npm` vs `yarn`, though.

**Comment by brandly** [comment]
sorry, didn't see this until now.

i'm also on OS X, so that's the only platform i've see this run on. i'd happily accept pull requests to get this running on other platforms tho

**Comment by brandly** [comment]
any updates here?

[the way i'm using `babel-register`](https://github.com/brandly/irc/blob/master/src/index.html#L17) is probably shakey. i've recently updated a lot of dependencies and restructured things internally which potentially helped the situation, but i still haven't ran this outside of OS X.

closing for now 🌟

**Comment by Fohlen** [comment]
Tested this today, works for me on OSX. Can try to test it on Linux as well.
