### ISSUE TITLE
distinguish "leave channel" from "show status changes"

### ISSUE THREAD

**Issue by tracker1** [brandly/irc#39]
The exit button in the top-right doesn't seem to `/part` the channel for you.

**Comment by brandly** [comment]
ah yeah, so i wanted a way to toggle showing join/part/quit in the message feed, but then the icon i grabbed definitely looks like it should `/part`. 

i'm thinking there should be either like a per-channel settings page, or maybe a small dropdown menu, that let's you toggle the visibility of these messages, toggle the visibility of the people list (#37), and exit the channel. that way, the actions will have some space to be clearly labelled.

**Comment by tracker1** [comment]
maybe:  `[X] Hide Channel Messages` ... or if you've used VS Code, have a bottom bar that has a visible item `Channel Messages: Visible` vs `Channel Messages: Hidden` where it will have them in the history, so prior show/part will show on toggle.

**Comment by tracker1** [comment]
The toggle for the people is a hard one... I'd prefer a left-carat around where the current exit-like icon is...  maybe the exit/part next to the name of the channel.

Or, vertical dots, with a menu for part, toggle users, etc.

**Comment by brandly** [comment]
closed via https://github.com/brandly/irc/commit/58afb7d7665cdf70315e4d5052b7464219416b4f

the available options are labelled now

<img width="208" alt="Screen Shot 2019-08-29 at 1 34 28 AM" src="https://user-images.githubusercontent.com/820696/63913177-308d8280-c9fd-11e9-8f26-6a289ed2d672.png">

for now, the only way to leave a channel is `/part`, but we should probably add a button in the dropdown as well.
