### ISSUE TITLE
Custom hostname option

### ISSUE THREAD

**Issue by xvilo** [brandly/irc#45]
Hi,

Generally, I want to use this client for a private IRC server. So giving another option for 'other' or by default, just an input field for the hostname would be highly appreciated :)

**Comment by brandly** [comment]
true! i made it a `<select>` mainly because i wanted it to feel more inviting, so even if you're new to IRC, you could hop on a server and start chatting.

have you seen a good UX approach to showing a dropdown while still supporting a plain input field when needed?

**Comment by brandly** [comment]
check out [v0.4.0](https://github.com/brandly/irc/releases/tag/0.4.0)!!
