### ISSUE TITLE
Bug: Private Message are sent to me

### ISSUE THREAD

**Issue by xvilo** [brandly/irc#48]
I connect through ZNC (not sure if that is an issue with it). But when I send a private message to a certain user, they will receive it. Unfortunately, when I get a message back from them, the message will go into the 'your username'-thread. For all private messages.

**Comment by brandly** [comment]
i don't know anything about ZNC, but here's what i found.

here's where we receive a `message` and dispatch it as a `RECEIVE_DIRECT_MESSAGE`:

https://github.com/brandly/irc/blob/5094c3d74578ca01dde37108f6cbde43cd519db6/src/js/actions/connections.js#L168-L174

IRC names are case-insensitive, but it's checking `if (e.to === nickname)`. there are a couple places names get compared [in this reducer](https://github.com/brandly/irc/blob/master/src/js/reducers/conversations.js) as well. 

i think we should define a case-insensitive name equality function [via `localCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) and use it wherever we compare names
