### ISSUE TITLE
Custom server?

### ISSUE THREAD

**Issue by LinuxGamer** [brandly/irc#50]
It's possible to join a custom server? by adding then or editing the a file?
because i want to use it to chat on osu!irc

**Comment by brandly** [comment]
I think this is a duplicate of #45. I should probably change the drop down to a normal input field for now, and then we can see if there’s a better way to kinda support both.

**Comment by brandly** [comment]
check out [v0.4.0](https://github.com/brandly/irc/releases/tag/0.4.0)!!
