### ISSUE TITLE
Default port

### ISSUE THREAD

**Issue by ajmas** [brandly/irc#60]
Should provide 6667 as a default port in the connection window.

**Comment by brandly** [comment]
[this is actually the case on `master`](https://github.com/brandly/irc/blob/master/src/js/reducers/creator.js#L9), but i guess there hasn't been a release in a long time

**Comment by brandly** [comment]
[i uploaded a build](https://github.com/brandly/irc/releases/tag/0.5.0-draft) which may be of use to you. as mentioned in that release, i don't think `master` is in a great state currently, but this default port issue has been handled.

thanks for the feedback! please keep filing issues. sorry i don't have a ton of time for this repo at the moment.
